USE [NAV100CU3_Overaasen]
GO

INSERT INTO [dbo].[Test Øveraasen Rapporter$OPC Time Register]
			([Machine Center]
		  ,[Start Date]
		  ,[Start Time]
		  ,[End Date]
		  ,[End Time]
		  ,[Quantity]
		  ,[Time Type]
		  ,[Absence]
		  ,[Date exported to Tempus]
		  ,[Actual Start Time]
		  ,[Description]
		  ,[Deduction Type])
	SELECT  [Machine Center]
		  ,[Start Date]
		  ,[Start Time]
		  ,[End Date]
		  ,[End Time]
		  ,[Quantity]
		  ,[Time Type]
		  ,[Absence]
		  ,[Date exported to Tempus]
		  ,[Actual Start Time]
		  ,[Description]
		  ,[Deduction Type]
 FROM [Nav2009_Overaasen].[dbo].[Øveraasen AS$Time Register-oas] 
 --and ([Entry No_] > 100)
GO