USE [NAV100CU3_Overaasen]
GO

INSERT INTO [dbo].[Test Øveraasen Rapporter$OPC Run Times]
			([Entry No_]
			,[Prod_ Order No_]
			,[Routing No_]
			,[Operation No_]
			,[Machine Center]
			,[Description]
			,[Starting Date]
			,[Starting Time]
			,[Ending Date]
			,[Ending Time]
			,[Finish Now]
			,[Posted]
			,[Work Done at M_C_]
			,[Stop Code])
	SELECT  [Entry No_]
			,[Prod_ Order No_]
			,[Routing No_]
			,[Operation No_]
			,[Machine Center]
			,[Description]
			,[Starting Date]
			,[Starting Time]
			,[Ending Date]
			,[Ending Time]
			,[Finish Now]
			,[Post]
			,[Work done at M_C_]
			,[Stop Code]
 FROM [Nav2009_Overaasen].[dbo].[Øveraasen AS$Run Times]
 where ([Entry No_] > 98) 
 --and ([Entry No_] > 100)
GO