USE [ReportServer]
DBCC SHRINKFILE (N'ReportServer' , 0, TRUNCATEONLY)


USE [ReportServer]
DBCC SHRINKFILE (N'ReportServer_log' , 0, TRUNCATEONLY)


USE [ReportServerTempDB]
DBCC SHRINKFILE (N'ReportServerTempDB' , 0, TRUNCATEONLY)


USE [ReportServerTempDB]
DBCC SHRINKFILE (N'ReportServerTempDB_log' , 0, TRUNCATEONLY)


USE [NAV_BL_NO]
DBCC SHRINKFILE (N'NAV_BL_NO_Data' , 0, TRUNCATEONLY)


USE [NAV_BL_NO]
DBCC SHRINKFILE (N'NAV_BL_NO_Log' , 0, TRUNCATEONLY)


USE [NAV_BL_NO]
DBCC SHRINKFILE (N'NAV_BL_NO_Data_1' , 0, TRUNCATEONLY)


USE [NAV_BL_NO]
DBCC SHRINKFILE (N'NAV_BL_NO_Log_2' , 0, TRUNCATEONLY)


USE [Demo Database NAV (7-1)]
DBCC SHRINKFILE (N'Demo Database NAV (7-1)_Data' , 0, TRUNCATEONLY)


USE [Demo Database NAV (7-1)]
DBCC SHRINKFILE (N'Demo Database NAV (7-1)_Log' , 0, TRUNCATEONLY)


USE [OtrumServiceNEW]
DBCC SHRINKFILE (N'Demo Database NAV (6-0)_Data' , 0, TRUNCATEONLY)


USE [OtrumServiceNEW]
DBCC SHRINKFILE (N'Demo Database NAV (6-0)_Log' , 0, TRUNCATEONLY)


USE [NAV2009R2_Form2Page]
DBCC SHRINKFILE (N'NAV2009R2_Form2Page_Data' , 0, TRUNCATEONLY)


USE [NAV2009R2_Form2Page]
DBCC SHRINKFILE (N'NAV2009R2_Form2Page_Log' , 0, TRUNCATEONLY)


USE [Demo Database NAV (6-0)]
DBCC SHRINKFILE (N'Demo Database NAV (6-0)_Data' , 0, TRUNCATEONLY)


USE [Demo Database NAV (6-0)]
DBCC SHRINKFILE (N'Demo Database NAV (6-0)_Log' , 0, TRUNCATEONLY)


USE [ITW2009]
DBCC SHRINKFILE (N'ITW2009_Data' , 0, TRUNCATEONLY)


USE [ITW2009]
DBCC SHRINKFILE (N'ITW2009_Log' , 0, TRUNCATEONLY)


USE [ITW2009]
DBCC SHRINKFILE (N'ITW2009_1_Data' , 0, TRUNCATEONLY)


USE [RSA_Nav50]
DBCC SHRINKFILE (N'Nav50_Data' , 0, TRUNCATEONLY)


USE [RSA_Nav50]
DBCC SHRINKFILE (N'Nav50_Log' , 0, TRUNCATEONLY)


USE [RSA_Nav50]
DBCC SHRINKFILE (N'Nav50_1_Data' , 0, TRUNCATEONLY)


USE [UF_Nav2009_3jun14]
DBCC SHRINKFILE (N'Nav2009_Data' , 0, TRUNCATEONLY)


USE [UF_Nav2009_3jun14]
DBCC SHRINKFILE (N'Nav2009_Log' , 0, TRUNCATEONLY)


USE [Nav2009_Overaasen]
DBCC SHRINKFILE (N'Nav2009_Overaasen_Data' , 0, TRUNCATEONLY)


USE [Nav2009_Overaasen]
DBCC SHRINKFILE (N'Nav2009_Overaasen_Log' , 0, TRUNCATEONLY)


USE [Nav2009_Overaasen]
DBCC SHRINKFILE (N'Nav2009_Overaasen_1_Data' , 0, TRUNCATEONLY)


USE [NAV2009SP1_OSO_Upgrade]
DBCC SHRINKFILE (N'NAV2009SP1_OSO_Upgrade_Data' , 0, TRUNCATEONLY)


USE [NAV2009SP1_OSO_Upgrade]
DBCC SHRINKFILE (N'NAV2009SP1_OSO_Upgrade_Log' , 0, TRUNCATEONLY)


USE [NAV2009SP1_OSO_Upgrade]
DBCC SHRINKFILE (N'NAV2009SP1_OSO_Upgrade_1_Data' , 0, TRUNCATEONLY)


USE [UF_Nav2009_3jun14_Test]
DBCC SHRINKFILE (N'Nav2009_Data' , 0, TRUNCATEONLY)


USE [UF_Nav2009_3jun14_Test]
DBCC SHRINKFILE (N'Nav2009_Log' , 0, TRUNCATEONLY)


USE [Demo Database NAV (8-0) CU6]
DBCC SHRINKFILE (N'Demo Database NAV (8-0)_Data' , 0, TRUNCATEONLY)


USE [Demo Database NAV (8-0) CU6]
DBCC SHRINKFILE (N'Demo Database NAV (8-0)_Log' , 0, TRUNCATEONLY)


USE [sysutility_mdw]
DBCC SHRINKFILE (N'sysutility_mdw_{1DC43E9D-9886-489F-9FFC-55C733E0A483}_DATA' , 0, TRUNCATEONLY)


USE [sysutility_mdw]
DBCC SHRINKFILE (N'sysutility_mdw_{1DC43E9D-9886-489F-9FFC-55C733E0A483}_LOG' , 0, TRUNCATEONLY)


USE [NAV71_ParmaPlast]
DBCC SHRINKFILE (N'DynamicsNAV71_Data' , 0, TRUNCATEONLY)


USE [NAV71_ParmaPlast]
DBCC SHRINKFILE (N'DynamicsNAV71_Log' , 0, TRUNCATEONLY)


USE [NAV2009_OSO_UpgradeToProd]
DBCC SHRINKFILE (N'NAV2009_OSO_UpgradeToProd_Data' , 0, TRUNCATEONLY)


USE [NAV2009_OSO_UpgradeToProd]
DBCC SHRINKFILE (N'NAV2009_OSO_UpgradeToProd_Log' , 0, TRUNCATEONLY)


USE [NAV2009_OSO_UpgradeToProd]
DBCC SHRINKFILE (N'NAV2009_OSO_UpgradeToProd_1_Data' , 0, TRUNCATEONLY)


USE [Demo Database NAV (7-0)]
DBCC SHRINKFILE (N'Demo Database NAV (7-0)_Data' , 0, TRUNCATEONLY)


USE [Demo Database NAV (7-0)]
DBCC SHRINKFILE (N'Demo Database NAV (7-0)_Log' , 0, TRUNCATEONLY)


USE [NAV50_SIData]
DBCC SHRINKFILE (N'NAV50_SIData_Data' , 0, TRUNCATEONLY)


USE [NAV50_SIData]
DBCC SHRINKFILE (N'NAV50_SIData_Log' , 0, TRUNCATEONLY)


USE [NAV50_SIData]
DBCC SHRINKFILE (N'NAV50_SIData_1_Data' , 0, TRUNCATEONLY)


USE [NAV50_SIData2Upgrade]
DBCC SHRINKFILE (N'NAV50_SIData2Upgrade_Data' , 0, TRUNCATEONLY)


USE [NAV50_SIData2Upgrade]
DBCC SHRINKFILE (N'NAV50_SIData2Upgrade_Log' , 0, TRUNCATEONLY)


USE [NAV50_SIData2Upgrade]
DBCC SHRINKFILE (N'NAV50_SIData2Upgrade_1_Data' , 0, TRUNCATEONLY)


USE [NAV50_SIData_Debug]
DBCC SHRINKFILE (N'Nav50_SIData_Debug_Data' , 0, TRUNCATEONLY)


USE [NAV50_SIData_Debug]
DBCC SHRINKFILE (N'Nav50_SIData_Debug_Log' , 0, TRUNCATEONLY)


USE [NAV50_SIData_Debug]
DBCC SHRINKFILE (N'Nav50_SIData_Debug_1_Data' , 0, TRUNCATEONLY)


USE [autogrip]
DBCC SHRINKFILE (N'autogrip_Data' , 0, TRUNCATEONLY)


USE [autogrip]
DBCC SHRINKFILE (N'autogrip_Log' , 0, TRUNCATEONLY)


USE [autogrip]
DBCC SHRINKFILE (N'autogrip_1_Data' , 0, TRUNCATEONLY)


USE [NAV2013R2_SIDATA]
DBCC SHRINKFILE (N'NAV2013R2_SIDATA_Data' , 0, TRUNCATEONLY)


USE [NAV2013R2_SIDATA]
DBCC SHRINKFILE (N'NAV2013R2_SIDATA_Log' , 0, TRUNCATEONLY)


USE [Demo Database NAV (8-0)]
DBCC SHRINKFILE (N'Demo Database NAV (8-0)_Data' , 0, TRUNCATEONLY)


USE [Demo Database NAV (8-0)]
DBCC SHRINKFILE (N'Demo Database NAV (8-0)_Log' , 0, TRUNCATEONLY)


USE [NAV2009R2_SIDATA]
DBCC SHRINKFILE (N'Demo Database NAV (6-0)_Data' , 0, TRUNCATEONLY)


USE [NAV2009R2_SIDATA]
DBCC SHRINKFILE (N'Demo Database NAV (6-0)_Log' , 0, TRUNCATEONLY)


USE [NAV2013R2_Handheld]
DBCC SHRINKFILE (N'NAV2013R2_Handheld_Data' , 0, TRUNCATEONLY)


USE [NAV2013R2_Handheld]
DBCC SHRINKFILE (N'NAV2013R2_Handheld_Log' , 0, TRUNCATEONLY)


USE [NAV2013CU18_UpgradeDB]
DBCC SHRINKFILE (N'NAV2013CU18_UpgradeDB_Data' , 0, TRUNCATEONLY)


USE [NAV2013CU18_UpgradeDB]
DBCC SHRINKFILE (N'NAV2013CU18_UpgradeDB_Log' , 0, TRUNCATEONLY)


USE [NAV2009SP1_OSO]
DBCC SHRINKFILE (N'NAV2009SP1_OSO_Data' , 0, TRUNCATEONLY)


USE [NAV2009SP1_OSO]
DBCC SHRINKFILE (N'NAV2009SP1_OSO_Log' , 0, TRUNCATEONLY)


USE [NAV2009SP1_OSO]
DBCC SHRINKFILE (N'NAV2009SP1_OSO_1_Data' , 0, TRUNCATEONLY)


USE [NAVUpgradeDBHelper]
DBCC SHRINKFILE (N'NAVUpgradeDBHelper' , 0, TRUNCATEONLY)


USE [NAVUpgradeDBHelper]
DBCC SHRINKFILE (N'NAVUpgradeDBHelper_log' , 0, TRUNCATEONLY)


USE [NAV2015CU1_OSO]
DBCC SHRINKFILE (N'NAV2015CU1_OSO_Data' , 0, TRUNCATEONLY)


USE [NAV2015CU1_OSO]
DBCC SHRINKFILE (N'NAV2015CU1_OSO_Log' , 0, TRUNCATEONLY)


USE [Demo Database NAV (6-0-NO-SP1)]
DBCC SHRINKFILE (N'Demo Database NAV (6-0-NO-SP1)_Data' , 0, TRUNCATEONLY)


USE [Demo Database NAV (6-0-NO-SP1)]
DBCC SHRINKFILE (N'Demo Database NAV (6-0-NO-SP1)_Log' , 0, TRUNCATEONLY)


USE [NAV2015CU1_OSO_Compello]
DBCC SHRINKFILE (N'NAV2015CU1_OSO_Compello_Data' , 0, TRUNCATEONLY)


USE [NAV2015CU1_OSO_Compello]
DBCC SHRINKFILE (N'NAV2015CU1_OSO_Compello_Log' , 0, TRUNCATEONLY)

